spring.application.name=petshop
logging.level.com.example.petshop=INFO

spring.jpa.show-sql=true

spring.datasource.url=jdbc:oracle:thin:@mibd_tp?TNS_ADMIN=/Users/trinicorvalan/Wallet_MIBD
spring.datasource.username=FULLSTACK_1
spring.datasource.password=Password.123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
